spring:
    cloud:
        stream:
            default:
                binder: rabbit
                contentType: application/json
            bindings:
                pollClosedOut-out-0:
                    destination: poll.results.output
                    producer:
                        requiredGroups: PollResultsConsumers
    data:
        mongodb:
            host: localhost
            port: 0
            database: itpolls
server.port: 8080

cpf-check-host: https://user-info.herokuapp.com/

jobs:
    closePolls:
        delayMillis: '1000'
        lock:
            id: 'closePollsLock'
            min: '0s'
            max: '0s'